import { DataSource, QueryRunner, Repository } from 'typeorm';
import { AuditLog } from '../../../infrastructures/databases/entities/audit-log.entity';
import { scopedRepository } from '../../../shared/utils/repository.util';
import { TaskStatus } from '../../task/constants/task-status.constant';

/** Fields needed to append one audit-log row. createdAt and id are generated by the DB. */
export interface ICreateAuditLogParams {
    taskId: string;
    actorId: string;
    actorName: string;
    fromStatus: TaskStatus;
    toStatus: TaskStatus;
}

/**
 * Data access for the append-only audit log. Exposes only insert and chronological
 * read: there is intentionally no update, delete, or soft-delete method, which is how
 * immutability is enforced at the persistence layer.
 */
export class AuditLogV1Repository {
    private readonly repo: Repository<AuditLog>;

    constructor(dataSource: DataSource) {
        this.repo = dataSource.getRepository(AuditLog);
    }

    /**
     * Appends one log row. Pass the status-change transaction's queryRunner so the
     * insert commits or rolls back together with the task status update.
     */
    async create(params: ICreateAuditLogParams, queryRunner?: QueryRunner): Promise<AuditLog> {
        const repo = scopedRepository(this.repo, queryRunner);
        return repo.save(repo.create(params));
    }

    /** Returns a task's logs oldest-first (the order the audit log is displayed in). */
    async findByTaskId(taskId: string): Promise<AuditLog[]> {
        return this.repo.find({ where: { taskId }, order: { createdAt: 'ASC' } });
    }
}
